version: '3'

services:
  notebook:
    build:
      context: .
      dockerfile: ./Dockerfile
    user: root
    environment:
      NB_UID: 1000
      NB_GID: 100
      GRANT_SUDO: "yes"
    privileged: true
    ports:
      - "8818:8818"
    restart: unless-stopped
    command: jupyter notebook --port 8818 --NotebookApp.token='genzitsu' --ip=0.0.0.0 --allow-root
